/*Copyright (c) 2017-2018 vanenburgsoftware.com All Rights Reserved.
 This software is the confidential and proprietary information of vanenburgsoftware.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with vanenburgsoftware.com*/

package com.hrdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.file.model.Downloadable;

import com.hrdb.models.query.*;

public interface HrdbQueryExecutorService {

    Page<ToBeApprovedLeavesResponse> executeToBeApprovedLeaves(String data, Pageable pageable);

    Downloadable exportToBeApprovedLeaves(ExportType exportType, String data, Pageable pageable);

    Integer executeLeaveAction(LeaveActionRequest leaveActionRequest);

}


