/*Copyright (c) 2017-2018 vanenburgsoftware.com All Rights Reserved.
 This software is the confidential and proprietary information of vanenburgsoftware.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with vanenburgsoftware.com*/
package com.hrdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class LeaveActionRequest implements Serializable {

    @NotNull
    @JsonProperty("status")
    private String status;
    @NotNull
    @JsonProperty("ID")
    private String id;

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof LeaveActionRequest)) return false;
        final LeaveActionRequest leaveActionRequest = (LeaveActionRequest) o;
        return Objects.equals(getStatus(), leaveActionRequest.getStatus()) &&
                Objects.equals(getId(), leaveActionRequest.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getStatus(),
                getId());
    }
}
